services:
  Media_creator:
    image: georgx22/mcp-media-creator:latest
    container_name: MCP Media Creator
    restart: always
    ports:
      - "8961:8961"
    environment:
      AWS_ACCESS_KEY: Your AWS access key
      AWS_REGION: Your AWS region, e.g. us-east-1
      AWS_SECRET_ACCESS_KEY: Your AWS secret access key
      S3_BUCKET: Name of your AWS S3 bucket